# Generated by Django 5.2 on 2025-05-07 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('protected', 'Protected')], default='private', max_length=10),
        ),
    ]
